spi:
  clk_pin: 18
  miso_pin: 19

one_wire:
  - platform: gpio
    pin: 4

debug:


text_sensor:
  - platform: debug
    reset_reason:
      name: "Stove Reset Reason"

sensor:
  - platform: wifi_signal
    name: "WiFi Signal dB"
    id: wifi_signal_db
    update_interval: 60s
    entity_category: "diagnostic"

  - platform: copy
    source_id: wifi_signal_db
    name: "WiFi Signal Percent"
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: "%"
    entity_category: "diagnostic"
    device_class: ""

  - platform: max6675
    name: "SMOKE_TEMP"
    id: temp_smoke
    cs_pin: 21
    update_interval: 2s
    filters:
      - median: { window_size: 5, send_every: 1 }
      - sliding_window_moving_average: { window_size: 3, send_every: 1 }

  - platform: dallas_temp
    id: temp_water
    address: 0x9f0192d446c62528
    name: "WATER_TEMP"
    update_interval: 2s
    filters:
      - sliding_window_moving_average: { window_size: 3, send_every: 1 }

binary_sensor:
  - platform: gpio
    pin:
      number: 16
      mode: INPUT_PULLDOWN
    name: "PHYSICAL_SWITCH"
    id: physical_sw
    filters:
      - delayed_on_off: 100ms
    on_press:
      - script.execute: sync_stove_state
    on_release:
      - script.execute: sync_stove_state
      - if:
          condition:
            switch.is_on: backup_heater
          then:
            - switch.turn_off: backup_heater
            - binary_sensor.template.publish:
                id: backup_status
                state: OFF
            - logger.log:
                tag: "SAFETY"
                level: INFO
                format: "SAFETY: Backup heater deactivated by physical switch"


  - platform: template
    name: "BACKUP_STATUS"
    id: backup_status
    lambda: |-
      return id(backup_heater).state;

switch:
  - platform: gpio
    pin: 25
    id: smoke_fan
    name: "SMOKE_FAN"
    internal: false
    restore_mode: ALWAYS_OFF
  
  - platform: gpio
    pin: 33
    id: spark_plug
    name: "SPARK_PLUG"
    internal: false
    restore_mode: ALWAYS_OFF

  - platform: gpio
    pin: 27
    id: backup_heater
    name: "BACKUP_HEATER"
    internal: false
    restore_mode: ALWAYS_OFF

  - platform: gpio
    pin: 26
    id: coclea
    name: "COCLEA_MOTOR"
    internal: false
    restore_mode: ALWAYS_OFF

  - platform: gpio
    pin: 32
    id: water_pump
    name: "WATER_PUMP"
    internal: false
    restore_mode: ALWAYS_OFF

  - platform: gpio
    pin: 14
    id: led_error
    internal: false
    restore_mode: ALWAYS_OFF

  - platform: gpio
    pin: 13
    id: led_warning
    internal: true
    restore_mode: ALWAYS_OFF

  - platform: gpio
    pin: 12
    id: led_ok
    internal: true
    restore_mode: ALWAYS_OFF